# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Wild & King Customizer"
handle = "wk-internal-customizer"
application_url = "http://localhost:3000"
embedded = true
client_id = "21102b2e2138173c5ab87e5ad38ef1e4"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_themes,write_themes"

[auth]
redirect_urls = [ "http://localhost:3000/api/auth/callback" ]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/orders-create"
  topics = [ "orders/create", "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/app-uninstalled"
  topics = [ "app/uninstalled" ]

[app_proxy]
url = "http://localhost:3000/api/proxy"
subpath = "customizer"
prefix = "apps"
